name = "RangeTrees"
uuid = "66b63344-7bd8-483a-a4f0-15733e6c45d1"
authors = ["Douglas Bates <dmbates@gmail.com> and contributors"]
version = "0.3.0"

[deps]
AbstractTrees = "1520ce14-60c1-5f80-bbc7-55ef81b5835c"

[compat]
AbstractTrees = "0.3, 0.4"
julia = "1.8"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
