name = "RangeTrees"
uuid = "66b63344-7bd8-483a-a4f0-15733e6c45d1"
authors = ["Douglas Bates <dmbates@gmail.com> and contributors"]
version = "0.1.0"

[compat]
julia = "1.8"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
